print('Hey I am Chappie, A Simple Chatbot.')
name = input('So Whats your name? ')
print('Nice to meet you ' + name)
age = input('How old are you? ')
print("Ohh... Unfortunately I dont have any age... :)")
print('I was porgrammed by a boy called Jayendu...')
print('He made me for an experiment.')
interests = input('BTW are you interested in computers? ')
print('Oh then its good')
interest_areas = input('In what things are you interested in Computers? ')
print('Very well, then you could learn and program a more intelligent A.I. program like me.')
hardware = input('Are you interseted in Computer Hardware? ' + hardware)
print('Ohh... Thats good then')
print('By all the results I have collected from you I will give you a last summary of you... :)')
print(name + ' is ')